### ISSUE TITLE
[Request] Has anyone tried creating a washing machine lovelace card?

### ISSUE THREAD

**Issue by ReX1983** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#181]
I have a Beko washer dryer that works perfectly in HA thanks to this integration (all the sensors are displayed & updated correctly - I have yet to try to send commands).

I was wondering if anyone has successfully created a card to display the sensors in a more compact version than the classic vertical-stack of entities/

Thanks!

**Comment by cnecrea** [comment]
Hi there.

Yeah, on the left side there is an "old" design created by myself. Right now I am working to create a new design card, more clean, more beautiful (i guess)

<img width="925" alt="image" src="https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/48139709/2fb5b0cf-88db-4a65-8dbb-4dbd7285193a">

This card is short right now because the washing machine is running ("in derulare" means "is running"). When is not, all options are available to select (condition based), like program, temperature, etc.

**Comment by cnecrea** [comment]
> I will leave this issue open but I changed labels to "wontfix" as a lovelace card would be in a separate repository. @cnecrea Let us know if and when you release your code and I can add a link in the Readme. I could also create a project under this organisation, if you are interested.

Many thanks! I still got some minor fix to do until is 100% working & simple to use. I will share the code and if you want you can include it in the readme file or include it in a new project. I'm happy to contribute with anything!

**Comment by townsmcp** [comment]
Sorry, what was the outcome with this in the end? Any links to instructions/code?

**Comment by alexreddy78** [comment]
> > I will leave this issue open but I changed labels to "wontfix" as a lovelace card would be in a separate repository. [@cnecrea](https://github.com/cnecrea) Let us know if and when you release your code and I can add a link in the Readme. I could also create a project under this organisation, if you are interested.
> 
> Many thanks! I still got some minor fix to do until is 100% working & simple to use. I will share the code and if you want you can include it in the readme file or include it in a new project. I'm happy to contribute with anything!
